baseURL = "https://anabel-decor.ru"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "Студия флористики Анабель"
theme = "anabel-decor"
publishDir = "docs"

[params]
    name = "Anna Anabel"
    description = 'Студия флористики и декора "Анабель"'
    phone = "+7(912)630-14-63"
	phone2 = "+7(343)271-07-97"
	email = "zubova123@mail.ru"
    address = "Екатеринбург Луначарского 182"
    year = "2013 - 2020"
    avatar = "images/guy.jpg"
    favicon = "images/gt_favicon.png"
    DateForm = "January 1, 2006"
	
    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = true
    showClients = true

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true

[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"


[[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1
[[menu.main]]
    name = "O нас"
    url = "/About/"
    weight = 2
[[menu.main]]
    name = "Контакты"
    url = "/contact/"
    weight = 5
[[menu.main]]
    name = "Проекты"
    url = "/project/"
    weight = 3
[[menu.main]]
    name = "Салон цветов ANABEL"
    url = "/buket/"
    weight = 4
[params.disqus]
    site = "anabel-decor.ru"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true



[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/anabeldecor"
    icon = "fab fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/anabel_decor/"
    icon = "fab fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	a-vk = "https://vk.com/anabel_decor"
	title = "vk"
	url = "https://vk.com/anabel_decor"
    icon = "images/vk.png"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:zubova123@mail.ru"
    icon = "fas fa-envelope-square"
    footer = false
    sharethis = true
    network = "email"
theme = "anabel-decor"
