name = "Anabel-decor"
license = "MIT"
licenselink = "https://github.com/ufo0906/anabel-decor/LICENSE.md"
description = ""
homepage = "https://ufo0906.github.io/anabel-decor/"
tags = ["blog","anabel","decor","","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
features = ["blog","responsive","personal","google analytics","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
min_version = "0.1"

[author]
  name = "UFO"
  homepage = "https://ufo0906.github.io/"

[original]
  name = "Anabel-decor"
  author = "UFO"
